# Generated by Django 4.1.4 on 2023-05-31 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_feature_delete_newsletter_delete_testimonial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='upload_time',
        ),
    ]
