# Generated by Django 4.1.4 on 2023-06-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterIndexTogether(
            name='menu',
            index_together={('id', 'slug')},
        ),
    ]
