# Generated by Django 4.1.4 on 2023-06-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_feature_newsletter_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_persons',
            field=models.IntegerField(default=1),
        ),
    ]
