# Generated by Django 4.1.4 on 2023-05-31 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
